import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function SceneEconomic(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/static/models/scene_cold.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
    actions.SwordAction.play();
    actions.FlagAction.play();
    actions.ChestAction.play();
    actions.Fishing_spearAction.play();
    actions.Wheel_barrowAction.play();
    
  });
  return (
    <group ref={group} {...props} dispose={null} position={[2700, -230, -1000]}>
      <group name="Scene" scale={23}>
        <mesh
          name="Flag"
          castShadow
          receiveShadow
          geometry={nodes.Flag.geometry}
          material={materials["PolyVikings_Material_01.137"]}
          rotation={[0.7, 0.881, 0.407]}
          scale={0.01}
        />
        <mesh
          name="Wheel_barrow"
          castShadow
          receiveShadow
          geometry={nodes.Wheel_barrow.geometry}
          material={materials["PolyVikings_Material_01.128"]}
          rotation={[0.7, 0.881, 0.407]}
          scale={0.01}
        />
        <mesh
          name="Sword"
          castShadow
          receiveShadow
          geometry={nodes.Sword.geometry}
          material={materials["PolyVikings_Material_01.129"]}
          rotation={[0.7, 0.881, 0.407]}
          scale={0.01}
        />
        <group
          name="SM_Wep_Sword_01031"
          rotation={[0.7, 0.881, 0.407]}
          scale={0.01}
        >
          <mesh
            name="Scene042"
            castShadow
            receiveShadow
            geometry={nodes.Scene042.geometry}
            material={materials["PolyVikings_Material_01.122"]}
          />
          <mesh
            name="Scene042_1"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_1.geometry}
            material={materials["PolyVikings_Material_01.108"]}
          />
          <mesh
            name="Scene042_2"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_2.geometry}
            material={materials["PolyVikings_Material_01.100"]}
          />
          <mesh
            name="Scene042_3"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_3.geometry}
            material={materials["PolyVikings_Material_01.102"]}
          />
          <mesh
            name="Scene042_4"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_4.geometry}
            material={materials["PolyVikings_Material_01.103"]}
          />
          <mesh
            name="Scene042_5"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_5.geometry}
            material={materials["PolyVikings_Material_01.104"]}
          />
          <mesh
            name="Scene042_6"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_6.geometry}
            material={materials["PolyVikings_Material_01.105"]}
          />
          <mesh
            name="Scene042_7"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_7.geometry}
            material={materials["PolyVikings_Material_01.168"]}
          />
          <mesh
            name="Scene042_8"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_8.geometry}
            material={materials["PolyVikings_Material_01.109"]}
          />
          <mesh
            name="Scene042_9"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_9.geometry}
            material={materials["PolyVikings_Material_01.148"]}
          />
          <mesh
            name="Scene042_10"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_10.geometry}
            material={materials["PolyVikings_Material_01.157"]}
          />
          <mesh
            name="Scene042_11"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_11.geometry}
            material={materials["PolyVikings_Material_01.110"]}
          />
          <mesh
            name="Scene042_12"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_12.geometry}
            material={materials["PolyVikings_Material_01.125"]}
          />
          <mesh
            name="Scene042_13"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_13.geometry}
            material={materials.PolyVikings_Material_01}
          />
          <mesh
            name="Scene042_14"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_14.geometry}
            material={materials["PolyVikings_Material_01.112"]}
          />
          <mesh
            name="Scene042_15"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_15.geometry}
            material={materials["PolyVikings_Material_01.113"]}
          />
          <mesh
            name="Scene042_16"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_16.geometry}
            material={materials["PolyVikings_Material_01.114"]}
          />
          <mesh
            name="Scene042_17"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_17.geometry}
            material={materials["PolyVikings_Material_01.094"]}
          />
          <mesh
            name="Scene042_18"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_18.geometry}
            material={materials["PolyVikings_Material_01.093"]}
          />
          <mesh
            name="Scene042_19"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_19.geometry}
            material={materials["PolyVikings_Material_01.099"]}
          />
          <mesh
            name="Scene042_20"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_20.geometry}
            material={materials["PolyVikings_Material_01.095"]}
          />
          <mesh
            name="Scene042_21"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_21.geometry}
            material={materials["PolyVikings_Material_01.139"]}
          />
          <mesh
            name="Scene042_22"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_22.geometry}
            material={materials["PolyVikings_Material_01.121"]}
          />
          <mesh
            name="Scene042_23"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_23.geometry}
            material={materials["PolyVikings_Material_01.117"]}
          />
          <mesh
            name="Scene042_24"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_24.geometry}
            material={materials["PolyVikings_Material_01.118"]}
          />
          <mesh
            name="Scene042_25"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_25.geometry}
            material={materials["PolyVikings_Material_01.119"]}
          />
          <mesh
            name="Scene042_26"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_26.geometry}
            material={materials["PolyVikings_Material_01.136"]}
          />
          <mesh
            name="Scene042_27"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_27.geometry}
            material={materials["PolyVikings_Material_01.120"]}
          />
          <mesh
            name="Scene042_28"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_28.geometry}
            material={materials["PolyVikings_Material_01.123"]}
          />
          <mesh
            name="Scene042_29"
            castShadow
            receiveShadow
            geometry={nodes.Scene042_29.geometry}
            material={materials["PolyVikings_Material_01.124"]}
          />
        </group>
        <mesh
          name="Fishing_spear"
          castShadow
          receiveShadow
          geometry={nodes.Fishing_spear.geometry}
          material={materials["PolyVikings_Material_01.126"]}
          rotation={[0.7, 0.881, 0.407]}
          scale={0.01}
        />
        <mesh
          name="Chest"
          castShadow
          receiveShadow
          geometry={nodes.Chest.geometry}
          material={materials["PolyVikings_Material_01.127"]}
          rotation={[0.7, 0.881, 0.407]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/static/models/scene_cold.glb");